# Generated by Django 3.0.8 on 2020-08-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='restrict_comments',
            field=models.BooleanField(default=False),
        ),
    ]
