# Generated by Django 3.0.8 on 2020-08-07 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora', '0006_question_restrict_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favourite_post',
            field=models.ManyToManyField(blank=True, related_name='favourite_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
