# Generated by Django 3.0.8 on 2020-09-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0008_auto_20200808_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='DOB',
        ),
    ]
